<?php
/**
 * @file
 * Enables option to upload covers to cover service.
 */

/**
 * Implements hook_menu().
 */
function ddb_cover_upload_menu() {
  $inc_path = drupal_get_path('module', 'ddb_cover_upload') . '/includes';

  $items['admin/config/cover_upload'] = array(
    'title' => 'Cover service',
    'description' => 'Upload an image to cover service.',
    'position' => 'left',
    'weight' => 0,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('upload cover'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/cover_upload/upload'] = array(
    'title' => 'Upload cover to cover service',
    'description' => 'Upload an image to cover service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ddb_cover_upload_form'),
    'access arguments' => array('upload cover'),
    'file' => 'ddb_cover_upload.admin.inc',
    'file path' => $inc_path,
  );

  $items['admin/config/cover_upload/submitted'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Communicating with cover service',
    'description' => 'Communicating with cover service.',
    'page callback' => 'ddb_cover_upload_submitted',
    'access arguments' => array('upload cover'),
    'file' => 'ddb_cover_upload.submitted.inc',
    'file path' => $inc_path,
  );

  $items['admin/config/cover_upload/upload/new'] = array(
    'title' => 'Upload cover to cover service',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['admin/config/cover_upload/upload/list'] = array(
    'title' => 'List uploaded covers',
    'page callback' => 'ddb_cover_upload_list',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'access arguments' => array('upload cover'),
    'file' => 'ddb_cover_upload.uploaded_list.inc',
    'file path' => $inc_path,
  );

  $items['admin/config/cover_upload/upload/settings'] = array(
    'title' => 'Cover upload settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ddb_cover_upload_settings_form'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'access arguments' => array('administer site configuration'),
    'file' => 'ddb_cover_upload.settings.inc',
    'file path' => $inc_path,
  );

  $items['cover_upload/ting_reference/autocomplete'] = array(
    'page callback' => '_cover_upload_ting_reference_autocomplete',
    'page arguments' => array(3),
    'access arguments' => array('upload cover'),
    'type' => MENU_CALLBACK,
    'file' => 'ddb_cover_upload.autocomplete.inc',
    'file path' => $inc_path,
  );

  $items['cover_upload/create_alt_image'] = array(
    'page callback' => '_cover_upload_create_alt_image',
    'file' => 'ddb_cover_upload.create_alt_image.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('upload cover'),
  );

  $items['cover_upload/check-submission'] = array(
    'page callback' => '_cover_upload_check_submission',
    'file' => 'ddb_cover_upload.submitted.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('upload cover'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ddb_cover_upload_permission() {
  return array(
    'upload cover' => array(
      'title' => t('Upload cover to cover service'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function ddb_cover_upload_theme($existing, $type, $theme, $path) {
  return array(
    'ddb_cover_upload_conditions' => array(
      'variables' => array(
        'copyright_text' => NULL
      ),
      'template' => 'ddb-cover-upload-conditions',
      'path' => $path . '/templates/'
    ),
    'ddb_cover_upload_best_result' => array(
      'variables' => array(),
      'template' => 'ddb-cover-upload-best-result',
      'path' => $path . '/templates/'
    ),
    'ddb_cover_upload_meta_left' => array(
      'variables' => array(
        'original_image' => NULL,
        'displayed_image' => NULL,
        'altered_time' => NULL,
        'adapt_link_title' => NULL
      ),
      'template' => 'ddb-cover-upload-meta-left',
      'path' => $path . '/templates/'
    ),
    'ddb_cover_upload_meta_data' => array(
      'variables' => array(
        'material' => NULL,
        'meta_data' => NULL
      ),
      'template' => 'ddb-cover-upload-meta-data',
      'path' => $path . '/templates/'
    ),
    'ddb_cover_upload_meta_copyright' => array(
      'variables' => array(
        'copyright_text' => NULL
      ),
      'template' => 'ddb-cover-upload-meta-copyright',
      'path' => $path . '/templates/'
    ),
    'ddb_cover_upload_submitted' => array(
      'variables' => array(
        'data' => NULL,
        'image' => NULL
      ),
      'template' => 'ddb-cover-upload-submitted',
      'path' => $path . '/templates/'
    ),
  );
}

/**
 * Store and retrieve variables from session.
 *
 * @param string $key
 *   Key to be set or got
 * @param $value
 *   Value to set for $key
 *
 * @return mixed
 *   If only $key is given, sought-after value for $key
 */
function _ddb_cover_upload_session(string $key, $value = null) {
  if (!is_null($value)) {
    unset($_SESSION[$key]);
    $_SESSION[$key] = $value;
  }

  if (isset($_SESSION[$key])) {
    return $_SESSION[$key];
  }
}
